"""Agent command - generate a new .na agent file from an intent string."""

import re
from pathlib import Path
from typing import Optional

import typer


def _slug(intent: str) -> str:
    """Convert an intent string to a snake_case filename slug."""
    s = intent.lower().strip()
    s = re.sub(r"[^a-z0-9]+", "_", s)
    return s.strip("_")


_AGENT_TEMPLATE = '''\
# agents/{slug}.na
# Intent: {intent}
# Generated by: aether agent "{intent}"
#
# Adapt the steps below to your domain.
# Use reason() to delegate LLM reasoning; chain calls to build context.


def run_{slug}(input: str) -> dict:
    """Run the {slug} agent.

    Args:
        input: Domain-specific input to process.

    Returns:
        A dict containing at minimum a "result" key.
    """
    # Step 1 — gather context relevant to the intent
    context = reason(
        "{intent} — gather relevant context for: " + input,
        context={{"raw_input": input}},
    )

    # Step 2 — apply reasoning over the gathered context
    analysis = reason(
        "{intent} — analyse and draw conclusions.",
        context=context,
    )

    # Step 3 — produce a structured result
    result = reason(
        "Summarise the outcome in one concise sentence.",
        context=analysis,
    )

    return {{
        "input": input,
        "context": context,
        "analysis": analysis,
        "result": result,
    }}
'''


def agent(
    intent: str,
    output: Optional[Path] = typer.Option(
        None, "--output", "-o", help="Output path (default: agents/<slug>.na)"
    ),
):
    """Generate a new Dana agent .na file from an intent description"""
    slug = _slug(intent)
    dest = output or Path("agents") / f"{slug}.na"

    dest.parent.mkdir(parents=True, exist_ok=True)

    if dest.exists():
        typer.echo(f"⚠ File already exists: {dest}  (skipping)")
        raise typer.Exit(1)

    dest.write_text(_AGENT_TEMPLATE.format(slug=slug, intent=intent))
    typer.echo(f"✓ Created {dest}")
    typer.echo(f"  Next: edit {dest}, then run `aether run`")
